### PR TITLE
Update readme 

### PR DESCRIPTION
**Pull request by kyracho**
update `preview.png`

preview

### CODE REVIEW

**Comment by Blankscreen-exe** [comment]
@kyracho I think it's on me. I really appreciate that you took your time out to contribute to my silly projects, but I actually wanted the light version of the page with the zigzag styling that is on the background. Not the dark one.

**Comment by kyracho** [comment]
@Blankscreen-exe No worries at all! I'll go ahead and change it to the light version with the zigzag styling on the background. Also, just a heads-up, the dark mode button isn't working anymore.  I apologize if the dark mode button issue was a result of my PR. I’ll work on fixing it!

**Comment by kyracho** [comment]
Sorry for not seeing this sooner! The issue occurred because the original `<h1>` element used the class `.text`, which was targeted in the `darkMode` function. After the dark mode button issue, the element was changed to use an id `title` instead, causing the `darkMode` function to fail when trying to apply changes to the now non-existent `.text` class. To resolve this, I’ll update the function to target the new `title` id instead of `.text`, like this:

```js
document.getElementById('title').classList.add('text-white');

```

**Comment by Blankscreen-exe** [comment]
Thank you for your time and efforts. Much appreciated. 😄

**Review by Blankscreen-exe — APPROVED** [review]

**Pull request merged**
